### PR TITLE
Add Consolas-Ligaturized font

### PR DESCRIPTION
**Pull request by zvizvi**

### CODE REVIEW

**Comment by Gaafar** [comment]
Thanks for the PR! can you also include woff2 font for the sake of optimization?

**Comment by zvizvi** [comment]
There is only this font version in the their repo :/

**Comment by Gaafar** [comment]
can you use this tool for converting the font. It will also generate a css file that you can modify & use

https://www.fontsquirrel.com/tools/webfont-generator

**Comment by zvizvi** [comment]
I added these font formats.
(converted by using transfonter.org)

**Comment by zvizvi** [comment]
@Gaafar

**Comment by Gaafar** [comment]
Thanks a lot @zvizvi 👍

**Pull request merged**
